export type CatalogItem={id:string;code:string;title:string;business:"Expert Academy"|"Expert Design"|"Expert Code";type:string;status:string;description:string;tags:string[];image:string;updated:string;relevance?:number;reason?:string};
export const catalogItems:CatalogItem[]=[
 {id:"stickers-space",code:"EXP-D7K4MX",title:"Stickers escolares — colección espacial",business:"Expert Design",type:"Producto",status:"En proceso",description:"Colección de stickers escolares creada con IA y preparada para impresión.",tags:["stickers","impresión","IA"],image:"stickers-space.svg",updated:"Hace 12 min",relevance:96,reason:"Incluye generación de stickers con IA, preparación para impresión y referencias visuales."},
 {id:"prompt-children",code:"EXP-P3L8QK",title:"Megaprompt de ilustración infantil",business:"Expert Design",type:"Prompt",status:"Listo",description:"Prompt reutilizable para producir ilustraciones infantiles consistentes.",tags:["prompt","ilustración","Gemini"],image:"cover-purple.svg",updated:"Ayer",relevance:89,reason:"El prompt genera ilustraciones por variables y complementa procesos creativos con Gemini."},
 {id:"python-class",code:"EXP-A4M8QW",title:"Clase 08 — Introducción a Python",business:"Expert Academy",type:"Clase",status:"Borrador",description:"Planificación práctica para introducir variables, tipos y estructuras básicas.",tags:["Python","clase","programación"],image:"academy-python.svg",updated:"Hace 2 h"},
 {id:"next-auth",code:"EXP-C9N2TX",title:"Starter de autenticación Next.js",business:"Expert Code",type:"Repositorio",status:"Probado",description:"Base reutilizable de autenticación segura para aplicaciones administrativas.",tags:["Next.js","auth","GitHub"],image:"code-auth.svg",updated:"Hace 3 días"},
 {id:"shirt-suppliers",code:"EXP-H6R4VT",title:"Proveedores — franelas de algodón",business:"Expert Design",type:"Recurso",status:"Referencia",description:"Directorio comparativo de proveedores, tallas, colores y condiciones.",tags:["franelas","proveedores"],image:"design-shirt-black.svg",updated:"Hace 5 días"},
 {id:"class-tools",code:"EXP-A8T2ML",title:"Herramientas para clases interactivas",business:"Expert Academy",type:"Colección",status:"Listo",description:"Recursos web para ejercicios, evaluaciones y dinámicas en clase.",tags:["clases","recursos","web"],image:"resource-web-grid.svg",updated:"Hace 1 semana"},
 {id:"print-flow",code:"EXP-W5F9CN",title:"Flujo de preparación para impresión",business:"Expert Design",type:"Workflow",status:"Probado",description:"Proceso completo desde el arte aprobado hasta el archivo final de impresión.",tags:["workflow","impresión"],image:"workflow-print.svg",updated:"Hace 4 días",relevance:84,reason:"Describe preparación técnica, revisión y salida final para impresión."},
];
export const businessTone=(business:CatalogItem["business"])=>business==="Expert Academy"?"academy":business==="Expert Design"?"design":"code";
export function filterCatalogItems(items:CatalogItem[],query:string){const normalized=query.trim().toLocaleLowerCase("es");if(!normalized)return items;return items.filter(item=>`${item.title} ${item.code} ${item.description} ${item.business} ${item.type} ${item.tags.join(" ")}`.toLocaleLowerCase("es").includes(normalized))}
